# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

{{- $ns := .Values.global.resourceReservation.namespace }}
{{- $sa := .Values.global.resourceReservation.serviceAccount }}
{{- if .Values.global.resourceReservation.createServiceAccount }}
{{- if not (lookup "v1" "ServiceAccount" $ns $sa) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa }}
  namespace: {{ $ns }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
{{- toYaml .Values.global.imagePullSecrets | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
