{
 "title": "Unifabric RDMA 节点",
 "tags": [
  "unifabric",
  "rdma",
  "node",
  "metrics"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "数据源", "query": "prometheus" },
   {
    "name": "cluster_name",
    "label": "集群",
    "query": {
     "query": "label_values(global_cluster_info, cluster_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(global_cluster_info{cluster_name=\"$cluster_name\"}, cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(unifabric_node_info{cluster=~\"$cluster\"}, unifabric_node_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "吞吐",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "按设备的读取吞吐利用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (parent_ifname) (\n  irate(unifabric_port_rcv_data{node_name=~\"$node\",cluster=~\"$cluster\"}[$__rate_interval])\n)\n/ sum by (parent_ifname) (unifabric_port_speed_mbps{node_name=~\"$node\",cluster=~\"$cluster\",is_root=\"true\"} * 1000000 / 8) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "按设备的写入吞吐利用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (parent_ifname) (\n  irate(unifabric_port_xmit_data{node_name=~\"$node\",cluster=~\"$cluster\"}[$__rate_interval])\n)\n/ sum by (parent_ifname) (unifabric_port_speed_mbps{node_name=~\"$node\",cluster=~\"$cluster\",is_root=\"true\"} * 1000000 / 8) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "按主机设备的读取吞吐",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by (parent_ifname) (\n  irate(unifabric_port_rcv_data{node_name=~\"$node\",cluster=~\"$cluster\"}[$__rate_interval])\n) * 8",
       "legendFormat": "{{parent_ifname}}"
      }
     ]
    },
    {
     "title": "按主机设备的写入吞吐",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by (parent_ifname) (\n  irate(unifabric_port_xmit_data{node_name=~\"$node\",cluster=~\"$cluster\"}[$__rate_interval])\n) * 8",
       "legendFormat": "{{parent_ifname}}"
      }
     ]
    },
    {
     "title": "按 Pod 设备的读取吞吐",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by (pod_namespace,pod_name,ifname) (\n  irate(unifabric_port_rcv_data{pod_name!=\"\", node_name=~\"$node\",cluster=~\"$cluster\"}[$__rate_interval])\n) * 8",
       "legendFormat": "{{pod_namespace}}/{{pod_name}} - {{ifname}}"
      }
     ]
    },
    {
     "title": "按 Pod 设备的写入吞吐",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by (pod_namespace,pod_name,ifname) (\n  irate(unifabric_port_xmit_data{pod_name!=\"\", node_name=~\"$node\",cluster=~\"$cluster\"}[$__rate_interval])\n) * 8",
       "legendFormat": "{{pod_namespace}}/{{pod_name}} - {{ifname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "基础（ECN/CNP/SEQ）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "按优先级的读取 Pause",
     "type": "timeseries",
     "description": "来源为 ethtool",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "sum by (ifname,priority) (\n    rate(unifabric_rx_pause{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
       "legendFormat": "{{ifname}} / priority{{priority}}"
      }
     ]
    },
    {
     "title": "按优先级的写入 Pause",
     "type": "timeseries",
     "description": "来源为 ethtool",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "targets": [
      {
       "expr": "sum by (ifname,priority) (\n    rate(unifabric_tx_pause{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
       "legendFormat": "{{ifname}} / priority{{priority}}"
      }
     ]
    },
    {
     "title": "按优先级的读取丢弃",
     "type": "timeseries",
     "description": "来源为 ethtool",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "sum by (ifname,priority) (\n    rate(unifabric_rx_discards{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
       "legendFormat": "{{ifname}} / priority{{priority}}"
      }
     ]
    },
    {
     "title": "按设备的 CNP 发送速率",
     "type": "timeseries",
     "description": "Notification Point 在 RoCEv2 IP 头（ECN 位）中察觉到拥塞后发送的 CNP 报文数。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_np_cnp_sent{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "按设备的 ECN 标记 RoCEv2 报文速率",
     "type": "timeseries",
     "description": "Notification Point 收到的、被标记为经历拥塞的 RoCEv2 报文数（入向 RoCE 流量的 ECN 位为 11）。\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_np_ecn_marked_roce_packets{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "按设备的 CNP 处理速率",
     "type": "timeseries",
     "description": "Reaction Point HCA 为限制发送速率而处理的 CNP 报文数。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_rp_cnp_handled{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\", is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "按设备的乱序报文速率",
     "type": "timeseries",
     "description": "收到的乱序报文数。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_out_of_sequence{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "按设备的 CNP 忽略速率",
     "type": "timeseries",
     "description": "Reaction Point HCA 收到但忽略的 CNP 报文数。网络中启用了 RoCE 拥塞控制时该计数不应增长，若增长请确认网卡已启用 ECN，参见 HowTo Configure DCQCN (RoCE CC) values for ConnectX-4 (Linux)。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_rp_cnp_ignored{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\", is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "明细",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "接收的 Write 请求",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_rx_write_requests{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "接收的 Read 请求",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 91 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_rx_read_requests{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "接收的 Atomic 请求",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 91 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_rx_atomic_requests{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\", is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "接收的 DCT 连接",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 91 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_rx_dct_connect{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "缓冲区不足",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_out_of_buffer{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "重复请求",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 98 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_duplicate_request{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "RNR NAK 重试错误",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 98 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_rnr_nak_retry_err{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "报文序号错误",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 98 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_packet_seq_err{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "隐含 NAK 序号错误",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 105 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(rdma_implied_nak_seq_err_total{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "本地 ACK 超时错误",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 105 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_local_ack_timeout_err{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "响应端本地长度错误",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 105 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_resp_local_length_error{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "响应端 CQE 错误",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 105 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_resp_cqe_error{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "请求端 CQE 错误",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 112 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_req_cqe_error{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "请求端远端无效请求",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 112 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_req_remote_invalid_request{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "请求端检测到的远端访问错误",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 112 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_resp_remote_access_errors{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "响应端 CQE Flush 错误",
     "type": "timeseries",
     "description": "响应端检测到 CQE 以 flush 错误完成的次数。",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 112 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(rdma_resp_cqe_flush_error_total{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "请求端 CQE Flush 错误",
     "type": "timeseries",
     "description": "请求端检测到 CQE 以 flush 错误完成的次数。\n",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 119 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_req_cqe_flush_error{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RoCE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "RoCE 自适应重传次数",
     "type": "timeseries",
     "description": "RoCE 流量的自适应重传次数。",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_roce_adp_retrans{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "RoCE 自适应重传超时次数",
     "type": "timeseries",
     "description": "RoCE 流量因自适应重传而超时的次数。",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_roce_adp_retrans_to{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "RoCE 慢启动次数",
     "type": "timeseries",
     "description": "使用 RoCE 慢启动的次数。",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_roce_slow_restart{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\", is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "RoCE 慢启动 CNP 次数",
     "type": "timeseries",
     "description": "RoCE 慢启动产生 CNP 报文的次数。",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_roce_slow_restart_cnps{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "RoCE 慢启动传输次数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_roce_slow_restart_trans{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "QoS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "流量类别",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum by (device, node_name, ifname, pod_name, pod_namespace) (unifabric_rdma_device_tos{node_name=~\"$node\", cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "接口", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "网络设备列表",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "unifabric_port_mtu{node=\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "unifabric_port_speed_mbps{node=\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "unifabric_port_oper_state{node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}