{
 "title": "Unifabric RDMA 集群",
 "tags": [
  "unifabric",
  "rdma",
  "cluster",
  "overview"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "数据源", "query": "prometheus" },
   {
    "name": "cluster_name",
    "label": "集群",
    "query": {
     "query": "label_values(global_cluster_info, cluster_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(global_cluster_info{cluster_name=\"$cluster_name\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "节点总数（具备 RDMA）",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(unifabric_port_rcv_data{pod_name!=\"\",cluster=~\"$cluster\"}) by (node_name))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Workload 总数（具备 RDMA）",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count by (topowner_kind, topowner_namespace, topowner_name) (unifabric_port_rcv_data{cluster=~\"$cluster\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pod 总数（具备 RDMA）",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(unifabric_port_rcv_data{pod_name!=\"\",cluster=~\"$cluster\"}) by (pod_name))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "集群读取总吞吐",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(\n  rate(unifabric_port_rcv_data{cluster=~\"$cluster\",host_rdma!=\"true\"}[$__rate_interval])\n) * 8",
       "legendFormat": "读取"
      }
     ]
    },
    {
     "title": "集群写入总吞吐",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(\n  rate(unifabric_port_xmit_data{cluster=~\"$cluster\",host_rdma!=\"true\"}[$__rate_interval])\n) * 8",
       "legendFormat": "写入"
      }
     ]
    },
    {
     "title": "按节点的读取吞吐",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by (node_name) (\n  rate(unifabric_port_rcv_data{cluster=~\"$cluster\",host_rdma!=\"true\"}[$__rate_interval])\n) * 8",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "按节点的写入吞吐",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by (node_name) (\n  rate(unifabric_port_xmit_data{cluster=~\"$cluster\",host_rdma!=\"true\"}[$__rate_interval])\n) * 8",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "按节点的读取吞吐利用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (node_name) (\n  rate(unifabric_port_rcv_data{cluster=~\"$cluster\",host_rdma!=\"true\"}[$__rate_interval])\n) * 8\n/\nsum by (node_name) (unifabric_port_speed_mbps{is_root=\"true\",cluster=~\"$cluster\",host_rdma!=\"true\"} * 1000000 / 8) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "按节点的写入吞吐利用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (node_name) (\n  rate(unifabric_port_xmit_data{cluster=~\"$cluster\",host_rdma!=\"true\"}[$__rate_interval])\n) * 8\n/\nsum by (node_name) (unifabric_port_speed_mbps{is_root=\"true\",cluster=~\"$cluster\",host_rdma!=\"true\"} * 1000000 / 8) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "热点",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "读取吞吐 Top 10 节点",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(\n  10,\n  sum by (node_name) (\n    rate(unifabric_port_rcv_data{cluster=~\"$cluster\",host_rdma!=\"true\"}[$__rate_interval])\n  ) * 8\n)",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "写入吞吐 Top 10 节点",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(\n  10,\n  sum by (node_name) (\n    rate(unifabric_port_xmit_data{cluster=~\"$cluster\",host_rdma!=\"true\"}[$__rate_interval])\n  ) * 8\n)",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "读取吞吐 Top 10 Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(\n  10,\n  sum by (pod_namespace,pod_name) (\n    rate(unifabric_port_rcv_data{cluster=~\"$cluster\",host_rdma!=\"true\",pod_name!=\"\"}[$__rate_interval])\n  ) * 8\n)",
       "legendFormat": "{{pod_namespace}}/{{pod_name}}"
      }
     ]
    },
    {
     "title": "写入吞吐 Top 10 Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(\n  10,\n  sum by (pod_namespace,pod_name) (\n    rate(unifabric_port_xmit_data{cluster=~\"$cluster\",host_rdma!=\"true\",pod_name!=\"\"}[$__rate_interval])\n  ) * 8\n)",
       "legendFormat": "{{pod_namespace}}/{{pod_name}}"
      }
     ]
    },
    {
     "title": "读取吞吐 Top 10 Workload",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(\n  10,\n  sum by (topowner_kind,topowner_namespace,topowner_name) (\n    rate(unifabric_port_rcv_data{cluster=~\"$cluster\", host_rdma!=\"true\", pod_name!=\"\", topowner_name!=\"\"}[$__rate_interval])\n  ) * 8\n)",
       "legendFormat": "{{topowner_kind}} - {{topowner_namespace}}/{{topowner_name}}"
      }
     ]
    },
    {
     "title": "写入吞吐 Top 10 Workload",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(\n  10,\n  sum by (topowner_kind,topowner_namespace,topowner_name) (\n    rate(unifabric_port_xmit_data{cluster=~\"$cluster\", host_rdma!=\"true\", pod_name!=\"\", topowner_name!=\"\"}[$__rate_interval])\n  ) * 8\n)",
       "legendFormat": "{{topowner_kind}} - {{topowner_namespace}}/{{topowner_name}}"
      }
     ]
    }
   ]
  },
  { "title": "节点状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "按节点 PF 的读取 Pause",
   "type": "timeseries",
   "description": "来源为 ethtool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (ifname,node_name) (\n    rate(unifabric_rx_pause{cluster=~\"$cluster\", pod_name=\"\", rdma_host!=\"true\"}[$__rate_interval])\n)",
     "legendFormat": "{{node_name}} / {{ifname}}"
    }
   ]
  },
  {
   "title": "按节点 PF 的写入 Pause",
   "type": "timeseries",
   "description": "来源为 ethtool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum by (ifname,node_name) (\n    rate(unifabric_tx_pause{pod_name=\"\", cluster=~\"$cluster\", rdma_host!=\"true\"}[$__rate_interval])\n)",
     "legendFormat": "{{node_name}} / {{ifname}}"
    }
   ]
  },
  {
   "title": "按节点 PF 的读取丢弃",
   "type": "timeseries",
   "description": "来源为 ethtool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (ifname,node_name) (\n    rate(unifabric_rx_discards{pod_name=\"\", cluster=~\"$cluster\", rdma_host!=\"true\"}[$__rate_interval])\n)",
     "legendFormat": "{{node_name}} / {{ifname}}"
    }
   ]
  },
  {
   "title": "按节点 PF 的 CNP 发送速率",
   "type": "timeseries",
   "description": "Notification Point 在 RoCEv2 IP 头（ECN 位）中察觉到拥塞后发送的 CNP 报文数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (device,ifname, node_name) (\n    rate(unifabric_np_cnp_sent{pod_name=\"\", is_root=\"true\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
     "legendFormat": "{{node_name}} / {{device}} / {{ifname}}"
    }
   ]
  },
  {
   "title": "按节点 PF 的 NP ECN 标记 RoCE 报文",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (device,ifname, node_name) (\n    rate(unifabric_np_ecn_marked_roce_packets{pod_name=\"\", is_root=\"true\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
     "legendFormat": "{{node_name}} / {{device}} / {{ifname}}"
    }
   ]
  },
  {
   "title": "按节点 PF 的 RP CNP 处理数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by (device,ifname, node_name) (\n    rate(unifabric_rp_cnp_handled{pod_name=\"\", is_root=\"true\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
     "legendFormat": "{{node_name}} / {{device}} / {{ifname}}"
    }
   ]
  },
  {
   "title": "按节点 PF 的乱序报文",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (device,ifname, node_name) (\n    rate(unifabric_out_of_sequence{pod_name=\"\", is_root=\"true\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
     "legendFormat": "{{node_name}} / {{device}} / {{ifname}}"
    }
   ]
  },
  {
   "title": "按节点 PF 的 RP CNP 忽略数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by (device,ifname, node_name) (\n    rate(unifabric_rp_cnp_ignored{pod_name=\"\", is_root=\"true\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
     "legendFormat": "{{node_name}} / {{device}} / {{ifname}}"
    }
   ]
  },
  { "title": "Pod 状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "按 Pod 的乱序报文（Top 10）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "topk(10,\n  sum by (pod_namespace, pod_name, device) (\n    rate(unifabric_out_of_sequence{pod_name!=\"\", cluster=~\"$cluster\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "{{pod_namespace}} / {{pod_name}} - {{device}}"
    }
   ]
  },
  {
   "title": "按 Pod 的读取丢弃（Top 10）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "topk(10,\n  sum by (pod_namespace,pod_name,device) (\n    rate(unifabric_rx_discards{pod_name!=\"\",cluster=~\"$cluster\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "{{pod_namespace}} / {{pod_name}} - {{device}}"
    }
   ]
  }
 ]
}