apiVersion: v2
appVersion: 0.4.23
description: A Helm chart for clusterResourceOverride
name: cro-operator
sources:
- https://github.com/fkajerry/dce-charts-repackage
type: application
version: 0.4.23
keywords:
  - cro-operator
  - cluster-resource-override
