apiVersion: v1
appVersion: 4.13.2
description: CSI NFS Driver for Kubernetes
name: csi-driver-nfs
version: 4.13.2
dependencies:
  - name: csi-driver-nfs
    version: "4.13.2"
    repository: "https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts"
keywords:
  - storage
