apiVersion: v2
name: "luscsi"
description: "A Helm chart for deploying LuCSI (Lustre CSI Driver) on Kubernetes"
type: "application"
version: "0.2.0"
appVersion: "0.2.0"

keywords:
  - "csi"
  - "storage"
  - "lustre"

home: "https://github.com/luskits/luscsi"
sources:
  - "https://github.com/luskits/luscsi"

maintainers:
  - name: "LuCSI Team"
    url: "https://github.com/luskits/luscsi"

