apiVersion: v2
appVersion: 0.15.2
description: Metax GPU kubernetes operator
name: metax-operator
type: application
version: 0.15.2
keywords:
  - gpu
  - compute
  - monitoring
  - telemetry

dependencies:
  - name: metax-operator
    version: 0.15.2