{{ include "llm-d-router.validations.epp" $ }}
{{ include "llm-d-router.inferencepool-resource" . }}
{{ include "llm-d-epp.config" . }}
{{ include "llm-d-epp.deployment" . }}
{{ include "llm-d-epp.leader-election-rbac" . }}
{{ include "llm-d-epp.sa-token-secret" . }}
{{ include "llm-d-epp.service" . }}
{{ include "llm-d-epp.service-monitor" . }}
