#!/bin/bash

CURRENT_FILENAME=$( basename "$0" )
CURRENT_DIR_PATH=$(cd `dirname $0` ; pwd )

KIND_KUBECONFIG=$1
CHART_DIR=$( cd ${CURRENT_DIR_PATH}/../../charts/istio-gateway/istio-gateway ; pwd )

[ -d "$CHART_DIR" ] || { echo "error, failed to find chart $CHART_DIR " ; exit 1 ; }
[ -f "$KIND_KUBECONFIG" ] || { echo "error, failed to find kubeconfig $KIND_KUBECONFIG " ; exit 1 ; }

echo "CHART_DIR: $CHART_DIR"
echo "KIND_KUBECONFIG: $KIND_KUBECONFIG"

HELM_MUST_OPTION=" --timeout 10m0s --wait --debug --kubeconfig ${KIND_KUBECONFIG} "

#==================== add your deploy code bellow =============
#==================== notice, prometheus CRD has been deployed , so you no need to =============
# !!!!!!!!! this chart is special, it does not contain any image, which make syncer-chart fail !!!!!!!!!

set -x

# deploy istio-gateway
# shellcheck disable=SC2086
# gateway.service.type=None  skip lb check
# gateway.replicaCount skip deployment check, cannot be deployed independently, because the mirror image is self-generated by istiod.
helm install istio-gateway "${CHART_DIR}" ${HELM_MUST_OPTION}  --namespace istio-system --create-namespace \
     --set gateway.service.type=None \
     --set gateway.autoscaling.enabled=false --set gateway.replicaCount=0

if (($?==0)) ; then
 echo "succeeded to deploy $CHART_DIR"
 exit 0
else
 echo "error, failed to deploy $CHART_DIR"
 exit 1
fi