apiVersion: v2
appVersion: 0.1.0-rc1
description: IaaS Network Provider — IPAM bridge between Spiderpool and Huawei Cloud
name: iaas-network-provider
type: application
version: 0.1.0-rc1
dependencies:
  - name: iaas-network-provider
    version: "0.1.0-rc1"
    repository: "oci://ghcr.io/daocloud/charts"
keywords:
  - kubernetes
  - networking
  - ipam
  - iaas
