- "{{ .registry }}/{{ .gpuLabel.image.name }}:{{ .gpuLabel.image.version }}"
- "{{ .registry }}/{{ .driver.image.name }}:{{ .driver.image.version }}"
- "{{ .registry }}/{{ .driver.payload.name }}:{{ .driver.payload.version }}"
- "{{ .registry }}/{{ .maca.image.name }}:{{ .maca.image.version }}"
- "{{ .registry }}/{{ .runtime.image.name }}:{{ .runtime.image.version }}"
- "{{ .registry }}/{{ .gpuDevice.image.name }}:{{ .gpuDevice.image.version }}"
- "{{ .registry }}/{{ .dataExporter.image.name }}:{{ .dataExporter.image.version }}"
- "{{ .registry }}/{{ .controller.name }}:{{ .controller.image.version }}"
- "{{ .registry }}/{{ .maca.payload.name }}:{{ .maca.payload.version}}"