{{- if eq (lower .Values.provider.name) "gke" }}
---
kind: HealthCheckPolicy
apiVersion: networking.gke.io/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway-api-inference-extension.labels" . | nindent 4 }}
spec:
  targetRef:
    group: inference.networking.k8s.io
    kind: InferencePool
    name: {{ .Release.Name }}
  default:
    # Set a more aggressive health check than the default 5s for faster switch
    # over during EPP rollout.
    timeoutSec: 2
    checkIntervalSec: 2
    {{- $port := .Values.inferencePool.targetPortNumber }}
    {{- if .Values.inferencePool.targetPorts }}
      {{- $port = (index .Values.inferencePool.targetPorts 0).number }}
    {{- end }}
    {{- if eq .Values.inferencePool.modelServerProtocol "http" }}
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /health
        port: {{ $port }}
    {{- else if and (eq (lower .Values.inferencePool.modelServerType) "vllm") (eq .Values.inferencePool.modelServerProtocol "grpc") }}
    config:
      type: GRPC
      grpcHealthCheck:
        portSpecification: "USE_FIXED_PORT"
        port: {{ $port }}
        grpcServiceName: "/vllm.grpc.engine.VllmEngine/HealthCheck"
    {{- end }}
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway-api-inference-extension.labels" . | nindent 4 }}
spec:
  targetRef:
    group: inference.networking.k8s.io
    kind: InferencePool
    name: {{ .Release.Name }}
  default:
    timeoutSec: 300    # 5-minute timeout (adjust as needed)
    logging:
      enabled: true    # log all requests by default
---
{{- end }}
{{- include "inference-extension.gke" . -}}
