apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "GPUExt.serviceAccountName" . }}
  namespace: {{ include "GPUExt.namespace" . }}
  labels:
    {{- include "GPUExt.labels" . | nindent 4 }}
    app.kubernetes.io/comonent: {{ include "GPUExt.serviceAccountName" . }}