{{- if .Values.topoDiscovery.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: topo-master-secret
  namespace: {{ include "GPUExt.namespace" . }}
data:
  username: {{ default "user" ((.Values.topoDiscovery).switchbox).clusterManagerUser }}
  password: {{ default "password" ((.Values.topoDiscovery).switchbox).clusterManagerPassword }}
{{- end }}