{{- define "llm-d-epp.leader-election-rbac" -}}
{{- if (.Values.router.epp.ha.enableLeaderElection | default false) }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "llm-d-router.name" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-d-router.labels" . | nindent 4 }}
rules:
- apiGroups: [ "coordination.k8s.io" ]
  resources: [ "leases" ]
  verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
- apiGroups: [ "" ]
  resources: [ "events" ]
  verbs: [ "create", "patch" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "llm-d-router.name" . }}-leader-election-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "llm-d-router.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "llm-d-router.name" . }}-leader-election
---
{{- end }}
{{- end }}
