{{- define "llm-d-epp.sa-token-secret" -}}
{{- $monitoringProviderName := include "llm-d-router.monitoring.provider.name" . | lower -}}
{{- if and .Values.router.monitoring.prometheus.enabled .Values.router.monitoring.prometheus.auth.enabled (eq $monitoringProviderName "prometheusoperator") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.router.monitoring.prometheus.auth.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-d-router.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "llm-d-router.name" . }}
type: kubernetes.io/service-account-token
---
{{- end }}
{{- end }}
