apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-data-exporter-sm
  namespace: {{ .Release.Namespace }}
  labels:
    operator.insight.io/managed-by: insight
spec:
  endpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: metax-data-exporter