apiVersion: apps/v1
kind: Deployment
metadata:
  name: grove-operator
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "operator.deployment.labels" . | nindent 4 }}
spec:
  replicas: {{ required ".Values.replicaCount is required" .Values.replicaCount }}
  selector:
    matchLabels:
{{- include "operator.deployment.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "operator.deployment.labels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Always
      {{- if .Values.priorityClass.enabled }}
      priorityClassName: {{ required ".Values.priorityClass.name is required" .Values.priorityClass.name }}
      {{- end }}
      serviceAccountName: {{ required ".Values.serviceAccount.name is required" .Values.serviceAccount.name }}
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.crdInstaller.enabled }}
      initContainers:
        - name: crd-installer
          image: {{ .Values.crdInstaller.image.registry }}/{{ include "image" .Values.crdInstaller.image }}
          imagePullPolicy: {{ .Values.crdInstaller.image.pullPolicy }}
          volumeMounts:
            - name: kube-api-access-grove
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
      {{- end }}
      containers:
        - name: grove-operator
          image: {{ .Values.image.registry }}/{{ include "image" .Values.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if and .Values.config.debugging .Values.config.debugging.enableProfiling }}
          ports:
            - name: pprof
              containerPort: {{ .Values.config.debugging.pprofBindPort }}
              protocol: TCP
          {{- end }}
          args:
            - --config=/etc/grove-operator/config/config.yaml
          {{- if .Values.config.server.healthProbes.enable }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ required ".Values.config.server.healthProbe.port is required" .Values.config.server.healthProbes.port }}
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ required ".Values.config.server.healthProbe.port is required" .Values.config.server.healthProbes.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
          {{- end }}
          {{- if .Values.resources }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: operator-config
              mountPath: /etc/grove-operator/config
            - name: kube-api-access-grove
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
            - name: grove-webhook-server-cert
              mountPath: {{ .Values.config.server.webhooks.serverCertDir | default "/etc/grove-operator/webhook-certs" }}
              readOnly: true
          env:
            - name: GROVE_OPERATOR_SERVICE_ACCOUNT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: GROVE_INIT_CONTAINER_IMAGE
              value: {{ .Values.initContainer.image.registry }}/{{ include "image" .Values.initContainer.image }}
{{- with .Values.deployment.env }}
{{- toYaml . | nindent 12 }}
{{- end }}
      volumes:
        - name: kube-api-access-grove
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 43200 # 12 hours
              - configMap:
                  name: kube-root-ca.crt
                  items:
                  - key: ca.crt
                    path: ca.crt
              - downwardAPI:
                  items:
                    - path: namespace
                      fieldRef:
                        fieldPath: metadata.namespace
                        apiVersion: v1
        - name: operator-config
          configMap:
            name: {{ include "operator.config.name" . }}
        - name: grove-webhook-server-cert
          # Mount the Secret volume containing webhook certificates
          secret:
            secretName: {{ .Values.config.server.webhooks.secretName | default "grove-webhook-server-cert" }}
            defaultMode: 420
            optional: true
