{{- if .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ required ".Values.metrics.serviceMonitor.name is required" .Values.metrics.serviceMonitor.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator.servicemonitor.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "operator.service.matchLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    path: /metrics
    scheme: http
{{- end }}
