{{- if and .Values.storage.enabled (not .Values.storage.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vllm-omni.fullname" . }}-model-cache
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "vllm-omni.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode | quote }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
{{- end }}
