{{- if .Values.huggingface.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vllm-omni.fullname" . }}-hf-token
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "vllm-omni.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.huggingface.token | quote }}
{{- end }}
