{
 "title": "Unifabric RDMA Cluster",
 "tags": [
  "unifabric",
  "rdma",
  "cluster",
  "overview"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": {
     "query": "label_values(global_cluster_info, cluster_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(global_cluster_info{cluster_name=\"$cluster_name\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Total (RDMA Capacity)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(unifabric_port_rcv_data{pod_name!=\"\",cluster=~\"$cluster\"}) by (node_name))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Workload Total (RDMA Capacity)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count by (topowner_kind, topowner_namespace, topowner_name) (unifabric_port_rcv_data{cluster=~\"$cluster\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pod Total (RDMA Capacity)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(unifabric_port_rcv_data{pod_name!=\"\",cluster=~\"$cluster\"}) by (pod_name))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cluster Read Throughput In Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(\n  rate(unifabric_port_rcv_data{cluster=~\"$cluster\",host_rdma!=\"true\"}[$__rate_interval])\n) * 8",
       "legendFormat": "Read"
      }
     ]
    },
    {
     "title": "Cluster Write Throughput In Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(\n  rate(unifabric_port_xmit_data{cluster=~\"$cluster\",host_rdma!=\"true\"}[$__rate_interval])\n) * 8",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Read Throughput by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by (node_name) (\n  rate(unifabric_port_rcv_data{cluster=~\"$cluster\",host_rdma!=\"true\"}[$__rate_interval])\n) * 8",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Write Throughput by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by (node_name) (\n  rate(unifabric_port_xmit_data{cluster=~\"$cluster\",host_rdma!=\"true\"}[$__rate_interval])\n) * 8",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Read Throughput Utilization by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (node_name) (\n  rate(unifabric_port_rcv_data{cluster=~\"$cluster\",host_rdma!=\"true\"}[$__rate_interval])\n) * 8\n/\nsum by (node_name) (unifabric_port_speed_mbps{is_root=\"true\",cluster=~\"$cluster\",host_rdma!=\"true\"} * 1000000 / 8) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Write Throughput Utilization by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (node_name) (\n  rate(unifabric_port_xmit_data{cluster=~\"$cluster\",host_rdma!=\"true\"}[$__rate_interval])\n) * 8\n/\nsum by (node_name) (unifabric_port_speed_mbps{is_root=\"true\",cluster=~\"$cluster\",host_rdma!=\"true\"} * 1000000 / 8) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Hotspot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 Read Throughput by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(\n  10,\n  sum by (node_name) (\n    rate(unifabric_port_rcv_data{cluster=~\"$cluster\",host_rdma!=\"true\"}[$__rate_interval])\n  ) * 8\n)",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 10 Write Throughput by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(\n  10,\n  sum by (node_name) (\n    rate(unifabric_port_xmit_data{cluster=~\"$cluster\",host_rdma!=\"true\"}[$__rate_interval])\n  ) * 8\n)",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 10 Read Throughput by Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(\n  10,\n  sum by (pod_namespace,pod_name) (\n    rate(unifabric_port_rcv_data{cluster=~\"$cluster\",host_rdma!=\"true\",pod_name!=\"\"}[$__rate_interval])\n  ) * 8\n)",
       "legendFormat": "{{pod_namespace}}/{{pod_name}}"
      }
     ]
    },
    {
     "title": "Top 10 Write Throughput by Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(\n  10,\n  sum by (pod_namespace,pod_name) (\n    rate(unifabric_port_xmit_data{cluster=~\"$cluster\",host_rdma!=\"true\",pod_name!=\"\"}[$__rate_interval])\n  ) * 8\n)",
       "legendFormat": "{{pod_namespace}}/{{pod_name}}"
      }
     ]
    },
    {
     "title": "Top 10 Read Throughput by Workload",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(\n  10,\n  sum by (topowner_kind,topowner_namespace,topowner_name) (\n    rate(unifabric_port_rcv_data{cluster=~\"$cluster\", host_rdma!=\"true\", pod_name!=\"\", topowner_name!=\"\"}[$__rate_interval])\n  ) * 8\n)",
       "legendFormat": "{{topowner_kind}} - {{topowner_namespace}}/{{topowner_name}}"
      }
     ]
    },
    {
     "title": "Top 10 Write Throughput by Workload",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(\n  10,\n  sum by (topowner_kind,topowner_namespace,topowner_name) (\n    rate(unifabric_port_xmit_data{cluster=~\"$cluster\", host_rdma!=\"true\", pod_name!=\"\", topowner_name!=\"\"}[$__rate_interval])\n  ) * 8\n)",
       "legendFormat": "{{topowner_kind}} - {{topowner_namespace}}/{{topowner_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Node Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Read Pause by by Node PF",
   "type": "timeseries",
   "description": "Source form ethtool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (ifname,node_name) (\n    rate(unifabric_rx_pause{cluster=~\"$cluster\", pod_name=\"\", rdma_host!=\"true\"}[$__rate_interval])\n)",
     "legendFormat": "{{node_name}} / {{ifname}}"
    }
   ]
  },
  {
   "title": "Write Pause by by Node PF",
   "type": "timeseries",
   "description": "Source form ethtool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum by (ifname,node_name) (\n    rate(unifabric_tx_pause{pod_name=\"\", cluster=~\"$cluster\", rdma_host!=\"true\"}[$__rate_interval])\n)",
     "legendFormat": "{{node_name}} / {{ifname}}"
    }
   ]
  },
  {
   "title": "Read Discards by Node PF",
   "type": "timeseries",
   "description": "Source form ethtool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (ifname,node_name) (\n    rate(unifabric_rx_discards{pod_name=\"\", cluster=~\"$cluster\", rdma_host!=\"true\"}[$__rate_interval])\n)",
     "legendFormat": "{{node_name}} / {{ifname}}"
    }
   ]
  },
  {
   "title": "CNP Packets Sent Rate by Node PF",
   "type": "timeseries",
   "description": "The number of CNP packets sent by the Notification Point when it noticed congestion experienced in the RoCEv2 IP header (ECN bits).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (device,ifname, node_name) (\n    rate(unifabric_np_cnp_sent{pod_name=\"\", is_root=\"true\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
     "legendFormat": "{{node_name}} / {{device}} / {{ifname}}"
    }
   ]
  },
  {
   "title": "NP ECN Marked ROCE Packets by Node PF",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (device,ifname, node_name) (\n    rate(unifabric_np_ecn_marked_roce_packets{pod_name=\"\", is_root=\"true\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
     "legendFormat": "{{node_name}} / {{device}} / {{ifname}}"
    }
   ]
  },
  {
   "title": "RP CNP Handled by Node PF",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by (device,ifname, node_name) (\n    rate(unifabric_rp_cnp_handled{pod_name=\"\", is_root=\"true\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
     "legendFormat": "{{node_name}} / {{device}} / {{ifname}}"
    }
   ]
  },
  {
   "title": "Out of Sequence by Node PF",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (device,ifname, node_name) (\n    rate(unifabric_out_of_sequence{pod_name=\"\", is_root=\"true\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
     "legendFormat": "{{node_name}} / {{device}} / {{ifname}}"
    }
   ]
  },
  {
   "title": "RP CNP Ignored by Node PF",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by (device,ifname, node_name) (\n    rate(unifabric_rp_cnp_ignored{pod_name=\"\", is_root=\"true\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
     "legendFormat": "{{node_name}} / {{device}} / {{ifname}}"
    }
   ]
  },
  { "title": "Pod Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Out of Sequence  by Pods (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "topk(10,\n  sum by (pod_namespace, pod_name, device) (\n    rate(unifabric_out_of_sequence{pod_name!=\"\", cluster=~\"$cluster\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "{{pod_namespace}} / {{pod_name}} - {{device}}"
    }
   ]
  },
  {
   "title": "Read Discards by Pods (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "topk(10,\n  sum by (pod_namespace,pod_name,device) (\n    rate(unifabric_rx_discards{pod_name!=\"\",cluster=~\"$cluster\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "{{pod_namespace}} / {{pod_name}} - {{device}}"
    }
   ]
  }
 ]
}