{
 "title": "Unifabric RDMA Node",
 "tags": [
  "unifabric",
  "rdma",
  "node",
  "metrics"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": {
     "query": "label_values(global_cluster_info, cluster_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(global_cluster_info{cluster_name=\"$cluster_name\"}, cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(unifabric_node_info{cluster=~\"$cluster\"}, unifabric_node_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Throughput Utilization by Device",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (parent_ifname) (\n  irate(unifabric_port_rcv_data{node_name=~\"$node\",cluster=~\"$cluster\"}[$__rate_interval])\n)\n/ sum by (parent_ifname) (unifabric_port_speed_mbps{node_name=~\"$node\",cluster=~\"$cluster\",is_root=\"true\"} * 1000000 / 8) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Write Throughput Utilization by Device",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (parent_ifname) (\n  irate(unifabric_port_xmit_data{node_name=~\"$node\",cluster=~\"$cluster\"}[$__rate_interval])\n)\n/ sum by (parent_ifname) (unifabric_port_speed_mbps{node_name=~\"$node\",cluster=~\"$cluster\",is_root=\"true\"} * 1000000 / 8) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Read Throughput by Host Device",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by (parent_ifname) (\n  irate(unifabric_port_rcv_data{node_name=~\"$node\",cluster=~\"$cluster\"}[$__rate_interval])\n) * 8",
       "legendFormat": "{{parent_ifname}}"
      }
     ]
    },
    {
     "title": "Write Throughput by Host Device",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by (parent_ifname) (\n  irate(unifabric_port_xmit_data{node_name=~\"$node\",cluster=~\"$cluster\"}[$__rate_interval])\n) * 8",
       "legendFormat": "{{parent_ifname}}"
      }
     ]
    },
    {
     "title": "Read Throughput by Pod Device",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by (pod_namespace,pod_name,ifname) (\n  irate(unifabric_port_rcv_data{pod_name!=\"\", node_name=~\"$node\",cluster=~\"$cluster\"}[$__rate_interval])\n) * 8",
       "legendFormat": "{{pod_namespace}}/{{pod_name}} - {{ifname}}"
      }
     ]
    },
    {
     "title": "Write Throughput by Pod Device",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by (pod_namespace,pod_name,ifname) (\n  irate(unifabric_port_xmit_data{pod_name!=\"\", node_name=~\"$node\",cluster=~\"$cluster\"}[$__rate_interval])\n) * 8",
       "legendFormat": "{{pod_namespace}}/{{pod_name}} - {{ifname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Basic (ECN/CNP/SEQ)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Pause by Priority",
     "type": "timeseries",
     "description": "Source form ethtool",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "sum by (ifname,priority) (\n    rate(unifabric_rx_pause{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
       "legendFormat": "{{ifname}} / priority{{priority}}"
      }
     ]
    },
    {
     "title": "Write Pause by Priority",
     "type": "timeseries",
     "description": "Source form ethtool",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "targets": [
      {
       "expr": "sum by (ifname,priority) (\n    rate(unifabric_tx_pause{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
       "legendFormat": "{{ifname}} / priority{{priority}}"
      }
     ]
    },
    {
     "title": "Read Discards by Priority",
     "type": "timeseries",
     "description": "Source form ethtool",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "sum by (ifname,priority) (\n    rate(unifabric_rx_discards{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
       "legendFormat": "{{ifname}} / priority{{priority}}"
      }
     ]
    },
    {
     "title": "CNP Packets Sent Rate by Device",
     "type": "timeseries",
     "description": "The number of CNP packets sent by the Notification Point when it noticed congestion experienced in the RoCEv2 IP header (ECN bits).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_np_cnp_sent{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "ECN Marked RoCEv2 Packets Rate by Device",
     "type": "timeseries",
     "description": "The number of RoCEv2 packets received by the notification point which were marked for experiencing the congestion (ECN bits where '11' on the ingress RoCE traffic) .\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_np_ecn_marked_roce_packets{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "CNP Packets Handled Rate by Device",
     "type": "timeseries",
     "description": "The number of CNP packets handled by the Reaction Point HCA to throttle the transmission rate.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_rp_cnp_handled{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\", is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "Out of Sequence Packets Rate by Device",
     "type": "timeseries",
     "description": "The number of out of sequence packets received.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_out_of_sequence{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "CNP Packets Ignored Rate by Device",
     "type": "timeseries",
     "description": "The number of CNP packets received and ignored by the Reaction Point HCA. This counter should not raise if RoCE Congestion Control was enabled in the network. If this counter raise, verify that ECN was enabled on the adapter. See HowTo Configure DCQCN (RoCE CC) values for ConnectX-4 (Linux).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_rp_cnp_ignored{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\", is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "RX Write Requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_rx_write_requests{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "RX Read Requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 91 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_rx_read_requests{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "RX Atomic Requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 91 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_rx_atomic_requests{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\", is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "RX DCT Connect",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 91 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_rx_dct_connect{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "Out of buffer",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_out_of_buffer{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "Duplicate Request",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 98 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_duplicate_request{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "RNR NAK Retry Error",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 98 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_rnr_nak_retry_err{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "Packet Seq Error",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 98 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_packet_seq_err{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "Implied NAK SEQ Error",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 105 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(rdma_implied_nak_seq_err_total{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "Local ACK Timeout Error",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 105 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_local_ack_timeout_err{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "Resp Local Length Error",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 105 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_resp_local_length_error{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "Resp CQE Error",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 105 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_resp_cqe_error{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "Req CQE Error",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 112 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_req_cqe_error{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "Req Remote Invalid Request",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 112 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_req_remote_invalid_request{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "Req detected Remote Access Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 112 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_resp_remote_access_errors{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "Resp CQE Flush Error",
     "type": "timeseries",
     "description": "The number of times responder detected CQEs completed with flushed errors.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 112 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(rdma_resp_cqe_flush_error_total{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "Req CQE Flush Error",
     "type": "timeseries",
     "description": "The number of times requester detected CQEs completed with flushed errors.\n",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 119 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_req_cqe_flush_error{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\",is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RoCE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "RoCE Adaptive Retransmissions Count",
     "type": "timeseries",
     "description": "Counts the number of adaptive retransmissions for RoCE traffic.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_roce_adp_retrans{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "RoCE Adaptive Retransmission Timeout Count",
     "type": "timeseries",
     "description": "Counts the number of times RoCE traffic reached timeout due to adaptive retransmission.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_roce_adp_retrans_to{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "RoCE Slow Restart Count",
     "type": "timeseries",
     "description": "Counts the number of times RoCE slow restart was used.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_roce_slow_restart{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\", is_root=\"true\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "RoCE Slow Restart CNP Count",
     "type": "timeseries",
     "description": "Counts the number of times RoCE slow restart generated CNP packets.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_roce_slow_restart_cnps{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    },
    {
     "title": "RoCE Slow Restart Trans Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum by (device,ifname) (\n    rate(unifabric_roce_slow_restart_trans{pod_name=\"\", node_name=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval])\n)",
       "legendFormat": "{{device}} / {{ifname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "QoS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic Class",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum by (device, node_name, ifname, pod_name, pod_namespace) (unifabric_rdma_device_tos{node_name=~\"$node\", cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Net Device List",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "unifabric_port_mtu{node=\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "unifabric_port_speed_mbps{node=\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "unifabric_port_oper_state{node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}