{{- if and (eq .Values.Agent.Builder.ContainerRuntime "podman") .Values.Agent.Builder.registriesConfig }}
apiVersion: v1
data:
  registries.conf: |
{{ .Values.Agent.Builder.registriesConfig | indent 4 }}
kind: ConfigMap
metadata:
  name: insecure-registries
  namespace: {{ include "jenkins.namespace" . }}
{{- end }}
