{{- $legacyServiceMonitorEnabled := dig "serviceMonitor" "enable" false .Values.scheduler }}
{{- $serviceMonitorEnabled := or .Values.prometheus.enabled $legacyServiceMonitorEnabled }}
{{- if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") $serviceMonitorEnabled }}
# Prometheus Service Monitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hami-vgpu.scheduler" . }}-metrics-monitor
  namespace: {{ include "hami-vgpu.namespace" . }}
  labels:
    app.kubernetes.io/component: hami-scheduler
    operator.insight.io/managed-by: insight
    {{- include "hami-vgpu.labels" . | nindent 4 }}
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: hami-scheduler
      {{- include "hami-vgpu.selectorLabels" . | nindent 6 }}
  endpoints:
    - interval: 15s
      metricRelabelings:
        - action: replace
          sourceLabels:
            - device_uuid
          targetLabel: deviceuuid
      path: /metrics
      port: monitor
{{- end }}
