# child values
llm-d-router-gateway:
  router:
    modelServers:
      matchLabels:
        app: inferx
    # matchLabels: # REQUIRED
    #   app: vllm-qwen3-32b
    epp:
      image:
        registry: ghcr.m.daocloud.io/llm-d
        repository: llm-d-router-endpoint-picker
        tag: v0.10.0
        pullPolicy: IfNotPresent
      resources:
        requests:
          cpu: "1"
          memory: 1Gi
        limits:
          cpu: "1"
          memory: 1Gi
      ha:
        enableLeaderElection: false
    latencyPredictor:
      trainingServer:
        image:
          registry: ghcr.m.daocloud.io/llm-d
          repository: llm-d-latency-predictor-training-server
          tag: v0.10.0
          pullPolicy: IfNotPresent
      predictionServers:
        image:
          registry: ghcr.m.daocloud.io/llm-d
          repository: llm-d-latency-predictor-prediction-server
          tag: v0.10.0
          pullPolicy: IfNotPresent
  # Gateway provider selection.
  # This section configures the gateway implementation only; it is not a generic infrastructure provider setting.
  # Options: ["gke", "istio", "none"]
  provider:
    name: none
    # Istio-specific configuration.
    # This block is only used if name is "istio".
    istio:
      destinationRule:
        # Provide a way to override the default calculated host
        host: ""
        # Optional: Enables customization of the traffic policy
        trafficPolicy: {}
        # connectionPool:
        #   http:
        #     maxRequestsPerConnection: 256000
    # GKE-specific configuration.
    # This block is only used if name is "gke".
    gke:
      preferredBackends:
        enabled: false
        # Number of primary active pod instances pinned to the PREFERRED load balancing tier.
        # Setting >1 scales concurrent active routing.
        preferredReplicas: 1
        # Number of standby pod instances pinned to the DEFAULT load balancing tier.
        # Setting >1 scales warm standby failover capacity.
        defaultReplicas: 1
        # Benchmark capacity and threshold settings for PREFERRED load balancing tier.
        # When incoming traffic exceeds capacityScalerPercent of maxRatePerEndpoint, excess traffic spills over to DEFAULT standby pods.
        balancingMode: RATE
        maxRatePerEndpoint: 100
        capacityScalerPercent: 100
  # httpRoute section is used to deploy an HTTPRoute resource as part of the gateway chart.
  httpRoute:
    create: false # a flag to indicate whether to create the httproute as part of the chart or not.
    inferenceGatewayName: inference-gateway
    inferenceGatewayNamespace: ""
    # HTTPRoute request timeout. Defaults to "300s". Unused when provider.name is gke.
    requestTimeout: "300s"
    # Example header matches:
    # headerMatches:
    #  x-my-custom-route-header: route-name
