- "{{ .kgateway.image.registry }}/{{ .kgateway.controller.image.repository }}:{{ .kgateway.image.tag }}"
- "{{ .kgateway.image.registry }}/{{ .kgateway.image.repository }}/envoy-wrapper:{{ .kgateway.image.tag }}"
