apiVersion: v1
kind: Service
metadata:
  name: {{ include "iaas-network-provider.fullname" . }}
  labels:
    {{- include "iaas-network-provider.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ ternary .Values.service.tlsPort .Values.service.port .Values.tls.enabled }}
      targetPort: {{ ternary "https" "http" .Values.tls.enabled }}
      protocol: TCP
      name: {{ ternary "https" "http" .Values.tls.enabled }}
      {{- if and (eq .Values.service.type "NodePort") (ternary .Values.service.nodePort.https .Values.service.nodePort.http .Values.tls.enabled) }}
      nodePort: {{ ternary .Values.service.nodePort.https .Values.service.nodePort.http .Values.tls.enabled }}
      {{- end }}
  selector:
    {{- include "iaas-network-provider.selectorLabels" . | nindent 4 }}
