apiVersion: v2
appVersion: 1.4.1
description: A Helm chart for NVIDIA Dynamo Platform.
home: https://nvidia.com
kubeVersion: '>=1.30.0-0'
maintainers:
  - name: NVIDIA, Inc.
    url: https://www.nvidia.com
name: dynamo-platform
type: application
version: 1.4.1
dependencies:
  - name: dynamo-platform
    version: "1.4.1"
    repository: "https://helm.ngc.nvidia.com/nvidia/ai-dynamo"
keywords:
  - ai
  - inference
annotations:
  images: |-
    - image: nvcr.m.daocloud.io/nvidia/ai-dynamo/kubernetes-operator:1.4.1
      name: dynamo-operator
    - image: docker.m.daocloud.io/library/nats:2.10.21-alpine
      name: nats
    - image: docker.m.daocloud.io/natsio/nats-server-config-reloader:0.16.0
      name: nats-server-config-reloader
    - image: docker.m.daocloud.io/natsio/prometheus-nats-exporter:0.16.0
      name: prometheus-nats-exporter
    - image: docker.m.daocloud.io/natsio/nats-box:0.14.5
      name: nats-box
    - image: ghcr.m.daocloud.io/ai-dynamo/grove/grove-operator:v0.1.0-alpha.12-rc1
      name: grove-operator
    - image: ghcr.m.daocloud.io/ai-dynamo/grove/grove-install-crds:v0.1.0-alpha.12-rc1
      name: grove-install-crds
    - image: ghcr.m.daocloud.io/ai-dynamo/grove/grove-initc:v0.1.0-alpha.12-rc1
      name: grove-initc
