apiVersion: v2
appVersion: v1.23.0
description: Helm chart for NVSentinel
name: nvsentinel
type: application
version: v1.23.0
dependencies:
  - name: nvsentinel
    version: "v1.23.0"
    repository: "oci://ghcr.io/nvidia"
keywords:
  - gpu
  - monitoring
  - nvsentinel
